laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('empresa', 'EmpresaController@index')->name('empresa');
    Route::get('produtos/{produtos_categoria?}', 'ProdutosController@index')->name('produtos');
    Route::get('produtos/{produtos_categoria}/{produtos_slug}', 'ProdutosController@show')->name('produtos.show');
    Route::get('informacoes-tecnicas', 'InformacoesTecnicasController@index')->name('informacoes-tecnicas');

    Route::get('profissionais', 'ProfissionaisController@interna')->name('profissionais')->middleware(['profissional']);
    Route::get('profissionais/login', 'ProfissionaisController@index')->name('profissionais.login');
    Route::get('profissionais/cadastro', 'ProfissionaisController@cadastro')->name('profissionais.cadastro');
    Route::post('profissionais/cadastro', 'ProfissionaisController@store')->name('profissionais.store');
    Route::post('profissionais/login', 'ProfissionalAuth\AuthController@login')->name('profissionais.login');
    Route::get('profissionais/logout', 'ProfissionalAuth\AuthController@logout')->name('profissionais.logout');

    Route::get('profissionais/redefinir', 'ProfissionaisController@esqueci')->name('profissionais.esqueci');
    Route::post('profissionais/redefinir', 'ProfissionalAuth\PasswordController@sendResetLinkEmail')->name('profissionais.redefinir');
    Route::get('profissionais/redefinicao/{token}', 'ProfissionalAuth\PasswordController@showResetForm');
    Route::post('profissionais/reset', 'ProfissionalAuth\PasswordController@reset')->name('profissionais.reset');

    Route::get('portfolio', 'AmbientesController@index')->name('portfolio');
    Route::get('portfolio/ambientes', 'AmbientesController@index')->name('ambientes');
    Route::get('portfolio/parceiros', 'ParceirosController@index')->name('parceiros');
    Route::get('portfolio/clipping', 'ClippingController@index')->name('clipping');
    Route::get('portfolio/showroom', 'ShowroomController@index')->name('showroom');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');

    Route::get('area-do-cliente', 'ClienteController@index')->name('cliente');
    Route::get('area-do-cliente/solicitacao', 'ClienteController@solicitacao')->name('cliente.solicitacao');
    Route::post('area-do-cliente/solicitacao', 'ClienteController@solicitacaoPost')->name('cliente.solicitacaoPost');
    Route::post('area-do-cliente/login', 'ClienteController@login')->name('cliente.login');
    Route::get('area-do-cliente/logout', 'ClienteController@logout')->name('cliente.logout');

    // Localização
    Route::get('lang/{idioma?}', function ($idioma = 'pt') {
        if ($idioma == 'pt' || $idioma == 'en' || $idioma == 'es') {
            Session::put('locale', $idioma);
        }
        return redirect()->route('home');
    })->name('lang');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
        Route::resource('cadastros', 'CadastrosController');
        Route::resource('gabaritos/categorias', 'GabaritosCategoriasController');
        Route::resource('gabaritos', 'GabaritosController');
		Route::resource('catalogos', 'CatalogosController');
        Route::resource('produtos/categorias', 'ProdutosCategoriasController');
        Route::resource('produtos', 'ProdutosController');
        Route::get('produtos/{produtos}/imagens/clear', [
            'as'   => 'painel.produtos.imagens.clear',
            'uses' => 'ProdutosImagensController@clear'
        ]);
        Route::resource('produtos.imagens', 'ProdutosImagensController');
        Route::resource('ambientes', 'AmbientesController');
        Route::resource('showroom', 'ShowroomController');
        Route::resource('parceiros', 'ParceirosController', ['only' => ['index', 'store', 'destroy']]);
        Route::get('clipping/delete-pdf/{clipping_id}', 'ClippingController@deletePdf')->name('painel.clipping.deletePdf');
        Route::get('clipping/delete-pdf-en/{clipping_id}', 'ClippingController@deletePdfEn')->name('painel.clipping.deletePdfEn');
        Route::get('clipping/delete-pdf-es/{clipping_id}', 'ClippingController@deletePdfEs')->name('painel.clipping.deletePdfEs');
		Route::resource('clipping', 'ClippingController');
		Route::resource('informacoes-tecnicas-video', 'InformacoesTecnicasVideoController', ['only' => ['index', 'update']]);
		Route::resource('informacoes-tecnicas', 'InformacoesTecnicasController');
		Route::resource('empresa', 'EmpresaController', ['only' => ['index', 'update']]);
		Route::resource('banners', 'BannersController');
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('solicitacoes', 'SolicitacoesController');
        Route::resource('usuarios', 'UsuariosController');

        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Http/Controllers/Painel/AmbientesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\AmbientesRequest;
use App\Http\Controllers\Controller;

use App\Models\Ambiente;
use App\Helpers\CropImage;

class AmbientesController extends Controller
{
    private $image_config = [
        [
            'width'   => 980,
            'height'  => null,
            'upsize'  => true,
            'marca'   => 'assets/painel/marcadagua/grande.png',
            'path'    => 'assets/img/ambientes/imagens/'
        ],
        [
            'width'   => 310,
            'height'  => 210,
            'marca'   => 'assets/painel/marcadagua/pequena.png',
            'path'    => 'assets/img/ambientes/'
        ]
    ];

    public function index()
    {
        $imagens = Ambiente::ordenados()->get();

        return view('painel.ambientes.index', compact('imagens'));
    }

    public function show(Ambiente $imagem)
    {
        return $imagem;
    }

    public function store(AmbientesRequest $request)
    {
        try {

            $input = $request->all();
            $input['imagem'] = CropImage::make('imagem', $this->image_config);

            $imagem = Ambiente::create($input);

            $view = view('painel.ambientes.imagem', compact('imagem'))->render();

            return response()->json(['body' => $view]);

        } catch (\Exception $e) {

            return 'Erro ao adicionar ambiente: '.$e->getMessage();

        }
    }

    public function update(AmbientesRequest $request, Ambiente $imagem)
    {
        try {

            $imagem->update([
                'legenda'    => $request->get('legenda'),
                'legenda_en' => $request->get('legenda_en'),
                'legenda_es' => $request->get('legenda_es')
            ]);

            return response()->json(['success' => 'Legenda alterada com sucesso']);

        } catch (\Exception $e) {

            return 'Erro ao alterar legenda: '.$e->getMessage();

        }
    }

    public function destroy(Ambiente $imagem)
    {
        try {

            $imagem->delete();
            return redirect()->route('painel.ambientes.index')
                             ->with('success', 'Ambiente excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir ambiente: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BannersRequest;
use App\Http\Controllers\Controller;

use App\Models\Banner;

class BannersController extends Controller
{
    public function index()
    {
        $registros = Banner::ordenados()->get();

        return view('painel.banners.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.banners.create');
    }

    public function store(BannersRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem_1'])) $input['imagem_1'] = Banner::upload_imagem_1();
            if (isset($input['imagem_2'])) $input['imagem_2'] = Banner::upload_imagem_2();
            if (isset($input['imagem_3'])) $input['imagem_3'] = Banner::upload_imagem_3();
            if (isset($input['imagem_4'])) $input['imagem_4'] = Banner::upload_imagem_4();
            if (isset($input['imagem_5'])) $input['imagem_5'] = Banner::upload_imagem_5();
            if (isset($input['imagem_6'])) $input['imagem_6'] = Banner::upload_imagem_6();

            Banner::create($input);
            return redirect()->route('painel.banners.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Banner $registro)
    {
        return view('painel.banners.edit', compact('registro'));
    }

    public function update(BannersRequest $request, Banner $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem_1'])) $input['imagem_1'] = Banner::upload_imagem_1();
            if (isset($input['imagem_2'])) $input['imagem_2'] = Banner::upload_imagem_2();
            if (isset($input['imagem_3'])) $input['imagem_3'] = Banner::upload_imagem_3();
            if (isset($input['imagem_4'])) $input['imagem_4'] = Banner::upload_imagem_4();
            if (isset($input['imagem_5'])) $input['imagem_5'] = Banner::upload_imagem_5();
            if (isset($input['imagem_6'])) $input['imagem_6'] = Banner::upload_imagem_6();

            $registro->update($input);
            return redirect()->route('painel.banners.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Banner $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.banners.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/CadastrosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Controllers\Controller;

use App\Models\Profissional;

class CadastrosController extends Controller
{
    public function index()
    {
        $registros = Profissional::all();

        return view('painel.profissionais.index', compact('registros'));
    }

    public function destroy(Profissional $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.cadastros.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/CatalogosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\CatalogosRequest;
use App\Http\Controllers\Controller;

use App\Models\Catalogo;

class CatalogosController extends Controller
{
    public function index()
    {
        $registros = Catalogo::ordenados()->get();

        return view('painel.catalogos.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.catalogos.create');
    }

    public function store(CatalogosRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['capa'])) $input['capa'] = Catalogo::upload_capa();
            if ($request->hasFile('pdf')) $input['pdf'] = Catalogo::uploadPdf();
            if ($request->hasFile('pdf_en')) $input['pdf_en'] = Catalogo::uploadPdfEn();
            if ($request->hasFile('pdf_es')) $input['pdf_es'] = Catalogo::uploadPdfEs();

            Catalogo::create($input);
            return redirect()->route('painel.catalogos.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Catalogo $registro)
    {
        return view('painel.catalogos.edit', compact('registro'));
    }

    public function update(CatalogosRequest $request, Catalogo $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['capa'])) $input['capa'] = Catalogo::upload_capa();
            if ($request->hasFile('pdf')) $input['pdf'] = Catalogo::uploadPdf();
            if ($request->hasFile('pdf_en')) $input['pdf_en'] = Catalogo::uploadPdfEn();
            if ($request->hasFile('pdf_es')) $input['pdf_es'] = Catalogo::uploadPdfEs();

            $registro->update($input);
            return redirect()->route('painel.catalogos.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Catalogo $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.catalogos.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/ContatoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ContatoRequest;
use App\Http\Controllers\Controller;

use App\Models\Contato;

class ContatoController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('painel.contato.index', compact('contato'));
    }

    public function update(ContatoRequest $request, Contato $contato)
    {
        try {

            $input = $request->all();

            $contato->update($input);
            return redirect()->route('painel.contato.index')->with('success', 'Informações alteradas com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar informações: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ContatosRecebidosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\ContatoRecebido;

class ContatosRecebidosController extends Controller
{
    public function index()
    {
        $contatosrecebidos = ContatoRecebido::orderBy('id', 'DESC')->paginate(15);

        return view('painel.contato.recebidos.index', compact('contatosrecebidos'));
    }

    public function show(ContatoRecebido $contato)
    {
        $contato->update(['lido' => 1]);

        return view('painel.contato.recebidos.show', compact('contato'));
    }

    public function destroy(ContatoRecebido $contato)
    {
        try {

            $contato->delete();
            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/EmpresaController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\EmpresaRequest;
use App\Http\Controllers\Controller;

use App\Models\Empresa;

class EmpresaController extends Controller
{
    public function index()
    {
        $registro = Empresa::first();

        return view('painel.empresa.edit', compact('registro'));
    }

    public function update(EmpresaRequest $request, Empresa $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Empresa::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.empresa.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/PainelController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use DB;

class PainelController extends Controller
{

    public function index()
    {
        return view('painel.home');
    }

    public function order(Request $request)
    {
        if (!$request->ajax()) return false;

        $data  = $request->input('data');
        $table = $request->input('table');

        for ($i = 0; $i < count($data); $i++) {
            DB::table($table)->where('id', $data[$i])->update(array('ordem' => $i + 1));
        }

        return json_encode($data);
    }

}

laravel/resources/views/painel/common/flash.blade.php
@if(session('success'))
   <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {!! session('success') !!}
    </div>
@endif

@if($errors->any())
    <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        @foreach($errors->all() as $error)
        {!! $error !!}<br>
        @endforeach
    </div>
@endif

laravel/resources/views/painel/common/nav.blade.php
<ul class="nav navbar-nav">
    <li @if(str_is('painel.banners*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.banners.index') }}">Banners</a>
    </li>
    <li @if(str_is('painel.empresa*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.empresa.index') }}">Empresa</a>
    </li>
    <li @if(str_is('painel.produtos*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.produtos.index') }}">Produtos</a>
    </li>
    <li @if(str_is('painel.informacoes-tecnicas*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.informacoes-tecnicas.index') }}">Informações Técnicas</a>
    </li>
    <li class="dropdown @if(str_is('painel.cadastros*', Route::currentRouteName()) || str_is('painel.catalogos*', Route::currentRouteName()) || str_is('painel.gabaritos*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Profissionais
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(str_is('painel.cadastros*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.cadastros.index') }}">Cadastros</a>
            </li>
            <li @if(str_is('painel.catalogos*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.catalogos.index') }}">Catálogos</a>
            </li>
            <li @if(str_is('painel.gabaritos*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.gabaritos.index') }}">Gabaritos</a>
            </li>
        </ul>
    </li>
    <li class="dropdown @if(str_is('painel.clipping*', Route::currentRouteName()) || str_is('painel.parceiros*', Route::currentRouteName()) || str_is('painel.ambientes*', Route::currentRouteName()) || str_is('painel.showroom*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Portfólio
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(str_is('painel.ambientes*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.ambientes.index') }}">Ambientes</a>
            </li>
            <li @if(str_is('painel.parceiros*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.parceiros.index') }}">Parceiros</a>
            </li>
            <li @if(str_is('painel.clipping*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.clipping.index') }}">Clipping</a>
            </li>
            <li @if(str_is('painel.showroom*', Route::currentRouteName())) class="active" @endif>
                <a href="{{ route('painel.showroom.index') }}">Showroom</a>
            </li>
        </ul>
    </li>
    <li @if(str_is('painel.solicitacoes*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.solicitacoes.index') }}">
            Solicitações
            @if($solicitacoesNaoLidos >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $solicitacoesNaoLidos }}</span>
            @endif
        </a>
    </li>
    <li class="dropdown @if(str_is('painel.contato*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Contato
            @if($contatosNaoLidos >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
            @endif
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li><a href="{{ route('painel.contato.index') }}">Informações de Contato</a></li>
            <li><a href="{{ route('painel.contato.recebidos.index') }}">
                Contatos Recebidos
                @if($contatosNaoLidos >= 1)
                <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
                @endif
            </a></li>
        </ul>
    </li>
</ul>

laravel/resources/views/painel/common/template.blade.php
<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <base href="{{ url('/') }}">

    <title>{{ config('site.name') }} - Painel Administrativo</title>

    <link rel="stylesheet" href="{{ asset('assets/vendor/bootswatch-dist/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendor/jquery-ui/themes/cupertino/jquery-ui.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/painel/growl/jquery.growl.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/painel/painel.css') }}">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url('/') }}">{{ config('site.name') }}</a>
            </div>

            <div id="navbar" class="navbar-collapse collapse">
                @include('painel.common.nav')

                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown @if(str_is('painel.usuarios*', Route::currentRouteName())) active @endif">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <span class="glyphicon glyphicon-cog small" style="margin-right:3px"></span>
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ route('painel.usuarios.index') }}">Usuários</a></li>
                            <li><a href="{{ route('logout') }}">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container" style="padding-bottom:30px;">
        @yield('content')
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{{ asset("assets/vendor/jquery/dist/jquery.min.js") }}"><\/script>')</script>
    <script src="{{ asset('assets/vendor/bootswatch-dist/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/jquery-ui/jquery-ui.min.js') }}"></script>
    <script src="{{ asset('assets/painel/growl/jquery.growl.js') }}"></script>
    <script src="{{ asset('assets/vendor/bootbox.js/bootbox.js') }}"></script>
    <script src="{{ asset('assets/vendor/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('assets/vendor/blueimp-file-upload/js/jquery.fileupload.js') }}"></script>
    <script src="{{ asset('assets/painel/painel.js') }}"></script>
</body>
</html>