laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('empresa', 'EmpresaController@index')->name('empresa');
    Route::get('produtos/{produtos_categoria?}', 'ProdutosController@index')->name('produtos');
    Route::get('produtos/{produtos_categoria}/{produtos_slug}', 'ProdutosController@show')->name('produtos.show');
    Route::get('informacoes-tecnicas', 'InformacoesTecnicasController@index')->name('informacoes-tecnicas');

    Route::get('profissionais', 'ProfissionaisController@interna')->name('profissionais')->middleware(['profissional']);
    Route::get('profissionais/login', 'ProfissionaisController@index')->name('profissionais.login');
    Route::get('profissionais/cadastro', 'ProfissionaisController@cadastro')->name('profissionais.cadastro');
    Route::post('profissionais/cadastro', 'ProfissionaisController@store')->name('profissionais.store');
    Route::post('profissionais/login', 'ProfissionalAuth\AuthController@login')->name('profissionais.login');
    Route::get('profissionais/logout', 'ProfissionalAuth\AuthController@logout')->name('profissionais.logout');

    Route::get('profissionais/redefinir', 'ProfissionaisController@esqueci')->name('profissionais.esqueci');
    Route::post('profissionais/redefinir', 'ProfissionalAuth\PasswordController@sendResetLinkEmail')->name('profissionais.redefinir');
    Route::get('profissionais/redefinicao/{token}', 'ProfissionalAuth\PasswordController@showResetForm');
    Route::post('profissionais/reset', 'ProfissionalAuth\PasswordController@reset')->name('profissionais.reset');

    Route::get('portfolio', 'AmbientesController@index')->name('portfolio');
    Route::get('portfolio/ambientes', 'AmbientesController@index')->name('ambientes');
    Route::get('portfolio/parceiros', 'ParceirosController@index')->name('parceiros');
    Route::get('portfolio/clipping', 'ClippingController@index')->name('clipping');
    Route::get('portfolio/showroom', 'ShowroomController@index')->name('showroom');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');

    Route::get('area-do-cliente', 'ClienteController@index')->name('cliente');
    Route::get('area-do-cliente/solicitacao', 'ClienteController@solicitacao')->name('cliente.solicitacao');
    Route::post('area-do-cliente/solicitacao', 'ClienteController@solicitacaoPost')->name('cliente.solicitacaoPost');
    Route::post('area-do-cliente/login', 'ClienteController@login')->name('cliente.login');
    Route::get('area-do-cliente/logout', 'ClienteController@logout')->name('cliente.logout');

    // Localização
    Route::get('lang/{idioma?}', function ($idioma = 'pt') {
        if ($idioma == 'pt' || $idioma == 'en' || $idioma == 'es') {
            Session::put('locale', $idioma);
        }
        return redirect()->route('home');
    })->name('lang');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
        Route::resource('cadastros', 'CadastrosController');
        Route::resource('gabaritos/categorias', 'GabaritosCategoriasController');
        Route::resource('gabaritos', 'GabaritosController');
		Route::resource('catalogos', 'CatalogosController');
        Route::resource('produtos/categorias', 'ProdutosCategoriasController');
        Route::resource('produtos', 'ProdutosController');
        Route::get('produtos/{produtos}/imagens/clear', [
            'as'   => 'painel.produtos.imagens.clear',
            'uses' => 'ProdutosImagensController@clear'
        ]);
        Route::resource('produtos.imagens', 'ProdutosImagensController');
        Route::resource('ambientes', 'AmbientesController');
        Route::resource('showroom', 'ShowroomController');
        Route::resource('parceiros', 'ParceirosController', ['only' => ['index', 'store', 'destroy']]);
        Route::get('clipping/delete-pdf/{clipping_id}', 'ClippingController@deletePdf')->name('painel.clipping.deletePdf');
        Route::get('clipping/delete-pdf-en/{clipping_id}', 'ClippingController@deletePdfEn')->name('painel.clipping.deletePdfEn');
        Route::get('clipping/delete-pdf-es/{clipping_id}', 'ClippingController@deletePdfEs')->name('painel.clipping.deletePdfEs');
		Route::resource('clipping', 'ClippingController');
		Route::resource('informacoes-tecnicas-video', 'InformacoesTecnicasVideoController', ['only' => ['index', 'update']]);
		Route::resource('informacoes-tecnicas', 'InformacoesTecnicasController');
		Route::resource('empresa', 'EmpresaController', ['only' => ['index', 'update']]);
		Route::resource('banners', 'BannersController');
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('solicitacoes', 'SolicitacoesController');
        Route::resource('usuarios', 'UsuariosController');

        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Http/Controllers/ClippingController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\Clipping;

class ClippingController extends Controller
{
    public function index()
    {
        return view('frontend.portfolio.clipping', [
            'clipping' => Clipping::ordenados()->get()
        ]);
    }
}

laravel/app/Http/Controllers/Painel/AmbientesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\AmbientesRequest;
use App\Http\Controllers\Controller;

use App\Models\Ambiente;
use App\Helpers\CropImage;

class AmbientesController extends Controller
{
    private $image_config = [
        [
            'width'   => 980,
            'height'  => null,
            'upsize'  => true,
            'marca'   => 'assets/painel/marcadagua/grande.png',
            'path'    => 'assets/img/ambientes/imagens/'
        ],
        [
            'width'   => 310,
            'height'  => 210,
            'marca'   => 'assets/painel/marcadagua/pequena.png',
            'path'    => 'assets/img/ambientes/'
        ]
    ];

    public function index()
    {
        $imagens = Ambiente::ordenados()->get();

        return view('painel.ambientes.index', compact('imagens'));
    }

    public function show(Ambiente $imagem)
    {
        return $imagem;
    }

    public function store(AmbientesRequest $request)
    {
        try {

            $input = $request->all();
            $input['imagem'] = CropImage::make('imagem', $this->image_config);

            $imagem = Ambiente::create($input);

            $view = view('painel.ambientes.imagem', compact('imagem'))->render();

            return response()->json(['body' => $view]);

        } catch (\Exception $e) {

            return 'Erro ao adicionar ambiente: '.$e->getMessage();

        }
    }

    public function update(AmbientesRequest $request, Ambiente $imagem)
    {
        try {

            $imagem->update([
                'legenda'    => $request->get('legenda'),
                'legenda_en' => $request->get('legenda_en'),
                'legenda_es' => $request->get('legenda_es')
            ]);

            return response()->json(['success' => 'Legenda alterada com sucesso']);

        } catch (\Exception $e) {

            return 'Erro ao alterar legenda: '.$e->getMessage();

        }
    }

    public function destroy(Ambiente $imagem)
    {
        try {

            $imagem->delete();
            return redirect()->route('painel.ambientes.index')
                             ->with('success', 'Ambiente excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir ambiente: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BannersRequest;
use App\Http\Controllers\Controller;

use App\Models\Banner;

class BannersController extends Controller
{
    public function index()
    {
        $registros = Banner::ordenados()->get();

        return view('painel.banners.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.banners.create');
    }

    public function store(BannersRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem_1'])) $input['imagem_1'] = Banner::upload_imagem_1();
            if (isset($input['imagem_2'])) $input['imagem_2'] = Banner::upload_imagem_2();
            if (isset($input['imagem_3'])) $input['imagem_3'] = Banner::upload_imagem_3();
            if (isset($input['imagem_4'])) $input['imagem_4'] = Banner::upload_imagem_4();
            if (isset($input['imagem_5'])) $input['imagem_5'] = Banner::upload_imagem_5();
            if (isset($input['imagem_6'])) $input['imagem_6'] = Banner::upload_imagem_6();

            Banner::create($input);
            return redirect()->route('painel.banners.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Banner $registro)
    {
        return view('painel.banners.edit', compact('registro'));
    }

    public function update(BannersRequest $request, Banner $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem_1'])) $input['imagem_1'] = Banner::upload_imagem_1();
            if (isset($input['imagem_2'])) $input['imagem_2'] = Banner::upload_imagem_2();
            if (isset($input['imagem_3'])) $input['imagem_3'] = Banner::upload_imagem_3();
            if (isset($input['imagem_4'])) $input['imagem_4'] = Banner::upload_imagem_4();
            if (isset($input['imagem_5'])) $input['imagem_5'] = Banner::upload_imagem_5();
            if (isset($input['imagem_6'])) $input['imagem_6'] = Banner::upload_imagem_6();

            $registro->update($input);
            return redirect()->route('painel.banners.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Banner $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.banners.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/CadastrosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Controllers\Controller;

use App\Models\Profissional;

class CadastrosController extends Controller
{
    public function index()
    {
        $registros = Profissional::all();

        return view('painel.profissionais.index', compact('registros'));
    }

    public function destroy(Profissional $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.cadastros.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/CatalogosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\CatalogosRequest;
use App\Http\Controllers\Controller;

use App\Models\Catalogo;

class CatalogosController extends Controller
{
    public function index()
    {
        $registros = Catalogo::ordenados()->get();

        return view('painel.catalogos.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.catalogos.create');
    }

    public function store(CatalogosRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['capa'])) $input['capa'] = Catalogo::upload_capa();
            if ($request->hasFile('pdf')) $input['pdf'] = Catalogo::uploadPdf();
            if ($request->hasFile('pdf_en')) $input['pdf_en'] = Catalogo::uploadPdfEn();
            if ($request->hasFile('pdf_es')) $input['pdf_es'] = Catalogo::uploadPdfEs();

            Catalogo::create($input);
            return redirect()->route('painel.catalogos.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Catalogo $registro)
    {
        return view('painel.catalogos.edit', compact('registro'));
    }

    public function update(CatalogosRequest $request, Catalogo $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['capa'])) $input['capa'] = Catalogo::upload_capa();
            if ($request->hasFile('pdf')) $input['pdf'] = Catalogo::uploadPdf();
            if ($request->hasFile('pdf_en')) $input['pdf_en'] = Catalogo::uploadPdfEn();
            if ($request->hasFile('pdf_es')) $input['pdf_es'] = Catalogo::uploadPdfEs();

            $registro->update($input);
            return redirect()->route('painel.catalogos.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Catalogo $registro)
    {
        try {

            $registro->delete();
            return redirect()->route('painel.catalogos.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/ContatoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ContatoRequest;
use App\Http\Controllers\Controller;

use App\Models\Contato;

class ContatoController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('painel.contato.index', compact('contato'));
    }

    public function update(ContatoRequest $request, Contato $contato)
    {
        try {

            $input = $request->all();

            $contato->update($input);
            return redirect()->route('painel.contato.index')->with('success', 'Informações alteradas com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar informações: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ContatosRecebidosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\ContatoRecebido;

class ContatosRecebidosController extends Controller
{
    public function index()
    {
        $contatosrecebidos = ContatoRecebido::orderBy('id', 'DESC')->paginate(15);

        return view('painel.contato.recebidos.index', compact('contatosrecebidos'));
    }

    public function show(ContatoRecebido $contato)
    {
        $contato->update(['lido' => 1]);

        return view('painel.contato.recebidos.show', compact('contato'));
    }

    public function destroy(ContatoRecebido $contato)
    {
        try {

            $contato->delete();
            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/EmpresaController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\EmpresaRequest;
use App\Http\Controllers\Controller;

use App\Models\Empresa;

class EmpresaController extends Controller
{
    public function index()
    {
        $registro = Empresa::first();

        return view('painel.empresa.edit', compact('registro'));
    }

    public function update(EmpresaRequest $request, Empresa $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Empresa::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.empresa.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/clipping/create.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Clipping /</small> Adicionar Clipping</h2>
    </legend>

    {!! Form::open(['route' => 'painel.clipping.store', 'files' => true]) !!}

        @include('painel.clipping.form', ['submitText' => 'Inserir'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/clipping/edit.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Clipping /</small> Editar Clipping</h2>
    </legend>

    {!! Form::model($registro, [
        'route'  => ['painel.clipping.update', $registro->id],
        'method' => 'patch',
        'files'  => true])
    !!}

    @include('painel.clipping.form', ['submitText' => 'Alterar'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/clipping/form.blade.php
@include('painel.common.flash')

<div class="form-group">
    {!! Form::label('data', 'Data') !!}
    {!! Form::text('data', null, ['class' => 'form-control monthpicker']) !!}
</div>

<div class="form-group">
    {!! Form::label('titulo', 'Título') !!}
    {!! Form::text('titulo', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('titulo_en', 'Título [INGLÊS]') !!}
    {!! Form::text('titulo_en', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('titulo_es', 'Título [ESPANHOL]') !!}
    {!! Form::text('titulo_es', null, ['class' => 'form-control']) !!}
</div>

<div class="well form-group">
    {!! Form::label('capa', 'Capa') !!}
@if($submitText == 'Alterar')
    <img src="{{ url('assets/img/clipping/'.$registro->capa) }}" style="display:block; margin-bottom: 10px; max-width: 100%;">
@endif
    {!! Form::file('capa', ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('link', 'Link') !!}
    {!! Form::text('link', null, ['class' => 'form-control']) !!}
</div>

<div class="row">
    <div class="col-md-4">
        <div class="form-group">
            {!! Form::label('pdf', 'PDF (se preenchido precede o link)') !!}
            @if($submitText == 'Alterar' && $registro->pdf)
            <p>
                <a href="{{ url('assets/pdfs/'.$registro->pdf) }}" target="_blank" style="display:block;">{{ $registro->pdf }}</a>
                <a href="{{ route('painel.clipping.deletePdf', $registro->id) }}" class="btn-delete btn-delete-link label label-danger">
                    <i class="glyphicon glyphicon-remove" style="margin-right:5px"></i>
                    REMOVER
                </a>
            </p>
            @endif
            {!! Form::file('pdf', ['class' => 'form-control']) !!}
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            {!! Form::label('pdf_en', 'PDF [INGLÊS] (se preenchido precede o link)') !!}
            @if($submitText == 'Alterar' && $registro->pdf_en)
            <p>
                <a href="{{ url('assets/pdfs/'.$registro->pdf_en) }}" target="_blank" style="display:block;">{{ $registro->pdf_en }}</a>
                <a href="{{ route('painel.clipping.deletePdfEn', $registro->id) }}" class="btn-delete btn-delete-link label label-danger">
                    <i class="glyphicon glyphicon-remove" style="margin-right:5px"></i>
                    REMOVER
                </a>
            </p>
            @endif
            {!! Form::file('pdf_en', ['class' => 'form-control']) !!}
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            {!! Form::label('pdf_es', 'PDF [ESPANHOL] (se preenchido precede o link)') !!}
            @if($submitText == 'Alterar' && $registro->pdf_es)
            <p>
                <a href="{{ url('assets/pdfs/'.$registro->pdf_es) }}" target="_blank" style="display:block;">{{ $registro->pdf_es }}</a>
                <a href="{{ route('painel.clipping.deletePdfEs', $registro->id) }}" class="btn-delete btn-delete-link label label-danger">
                    <i class="glyphicon glyphicon-remove" style="margin-right:5px"></i>
                    REMOVER
                </a>
            </p>
            @endif
            {!! Form::file('pdf_es', ['class' => 'form-control']) !!}
        </div>
    </div>
</div>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.clipping.index') }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/clipping/index.blade.php
@extends('painel.common.template')

@section('content')

    @include('painel.common.flash')

    <legend>
        <h2>
            Clipping
            <a href="{{ route('painel.clipping.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Clipping</a>
        </h2>
    </legend>

    @if(!count($registros))
    <div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>
    @else
    <table class="table table-striped table-bordered table-hover table-info">
        <thead>
            <tr>
                <th>Data</th>
                <th>Título</th>
                <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)
            <tr class="tr-row" id="{{ $registro->id }}">
                <td>{{ $registro->data }}</td>
                <td>{{ $registro->titulo }}</td>
                <td class="crud-actions">
                    {!! Form::open([
                        'route'  => ['painel.clipping.destroy', $registro->id],
                        'method' => 'delete'
                    ]) !!}

                    <div class="btn-group btn-group-sm">
                        <a href="{{ route('painel.clipping.edit', $registro->id ) }}" class="btn btn-primary btn-sm pull-left">
                            <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                    </div>

                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>

    @endif

@endsection